Tenn.is/Models/Article.cs
namespace Tennis.Models
{
    public class Article
    {
        public int ArticleID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int? AuthorID { get; set; }
        public DateTime TimeStamp { get; set; }
        public DateTime? LastEdited { get; set; }
        public string? ImgPath { get; set; }

        public Article(int articleId, string title, string content, int? authorId, DateTime timeStamp, DateTime? lastEdited, string? imgPath)
        {
            ArticleID = articleId;
            Title = title;
            Content = content;
            TimeStamp = timeStamp;
            AuthorID = authorId;
            LastEdited = lastEdited;
            ImgPath = imgPath;
        }

        //public Article(string title, string content, string? imgPath)
        //{
        //    Title = title;
        //    Content = content;
        //    if (ImgPath != null) ImgPath = imgPath;
        //}
        public Article(string title, string content)
        {
            Title = title;
            Content = content;
        }
        public Article()
        {
            
        }
    }
}

Tenn.is/Pages/Articles/CreateArticle.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;
using Tennis.Services;

namespace Tennis.Pages.Articles
{
    public class CreateArticleModel : PageModel
    {
        [BindProperty]
        public string ArticleTitle { get; set; }
        [BindProperty]
        public string ArticleContent { get; set; }

        public ArticleService _articleService;
        public CreateArticleModel(IArticleService articleService)
        {
            _articleService = new ArticleService(false);
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            Article newArticle = new Article(ArticleTitle, ArticleContent);
            _articleService.CreateArticle(newArticle);
            return RedirectToPage("/Articles/Index");
        }
    }
}

Tenn.is/Pages/Articles/EditArticle.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;
using Tennis.Services;

namespace Tennis.Pages.Articles
{
    public class EditArticleModel : PageModel
    {
        [BindProperty] public int ArticleID { get; set; }

        [BindProperty] public Article NewArticle { get; set; }


        private IArticleService _articleService {  get; set; }
        public EditArticleModel(IArticleService articleService)
        {
            _articleService = new ArticleService(false);
        }

        public void OnGet(int id)
        {
            NewArticle = _articleService.GetArticleById(id);
        }

        public IActionResult OnPost(int id)
        {

            _articleService.EditArticle(NewArticle, id);


            return RedirectToPage("Index");
        }

    }
}

Tenn.is/Pages/Articles/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using Tennis.Interfaces;
using Tennis.Models;
using Tennis.Services;

namespace Tennis.Pages.Articles
{
    public class IndexModel : PageModel
    {

        public bool IsLoggedIn = false;
        public bool IsAdmin = false;
        public string Username = string.Empty;

        public List<Article> AllArticles { get; set; }
        [BindProperty(SupportsGet = true)] public string Sorting { get; set; } = "Initial";

        [BindProperty(SupportsGet = true)] public string SearchFilter { get; set; }
        [BindProperty(SupportsGet = true)] public bool IsChecked { get; set; }




        public UserService _userService {  get; set; }

        private IArticleService _articleService;
        public IndexModel(IArticleService articleService)
        {
            _articleService = new ArticleService(false);
        }


        public void OnGet()
        {
            if (SearchFilter.IsNullOrEmpty())
            {
                DisplayAllArticles();
            }
            else
            {
                if (IsChecked)
                {
                    FilterBySearchPlusContent();
                }
                else
                {
                    FilterBySearch();
                }
            }
            #region User check (TODO)
            //    if (_userService.VerifyUser(HttpContext.Session.GetString("Username"), HttpContext.Session.GetString("Password")) != null)
            //    {
            //        IsLoggedIn = true;
            //        Username = HttpContext.Session.GetString("Username");

            //        if (_userService.AdminVerify(Username, HttpContext.Session.GetString("Password"))) 
            //        {
            //            IsAdmin = true;
            //        }
            //        else { IsAdmin = false; }
            //    } 
            //    else { IsLoggedIn = false; }
            #endregion
        }
        public void DisplayAllArticles()
        {
            AllArticles = _articleService.GetAllArticles().OrderByDescending(a => a.TimeStamp).ToList();
        }


        public void FilterBySearch()
        {
            AllArticles = _articleService.SearchArticlesDefault(SearchFilter);
        }
        public void FilterBySearchPlusContent()
        {
            AllArticles = _articleService.SearchArticlesContent(SearchFilter);
        }

        public void OrderArticles()
        {
            AllArticles.OrderByDescending(a => a.TimeStamp);
        }

        public IActionResult OnPostSorting()
        {
            return RedirectToPage("Index");
        }


        public IActionResult OnPost(int id)
        {
            _articleService.DeleteArticle(id);
            return RedirectToPage("Index");
        }
        
    }
}

Tenn.is/Pages/Lanes/LaneDelete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Pages.Lanes
{
    public class LaneDeleteModel : PageModel
    {
        ILaneService Service;
        [BindProperty]
        public Lane DelLane { get; set; }

        public LaneDeleteModel(ILaneService service)
        {
            Service = service;
        }

        public IActionResult OnGet(int Id)
        {
            DelLane = Service.GetLaneByNumber(Id);
            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            Service.DeleteLane(id);
            return RedirectToPage("LaneIndex");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("LaneIndex");
        }
    }
}

Tenn.is/Pages/Articles/CreateArticle.cshtml
@page
@model Tennis.Pages.Articles.CreateArticleModel
@{
}
<div class="card cardouter p-3">
<form method="post">
    <div class="form-group">
        <label for="ArticleTitle">Titel</label>
        <input type="text" class="form-control" name="ArticleTitle" placeholder="">
    </div>
    <div class="form-group">
        <label for="ArticleContent">Brødtekst</label>
        <input type="text" class="form-control" name="ArticleContent" placeholder="">
    </div>
@*     <div class="form-group">
        <label for="formInputImage">Image</label>
        <input type="file" class="form-control-file" id="formInputImage">
    </div> *@
    <button type="submit" class="btn btn-outline-success mb-2">Opret</button>
</form>
</div>

Tenn.is/Pages/Articles/EditArticle.cshtml
@page
@model Tennis.Pages.Articles.EditArticleModel
@{
}
<div class="card cardouter p-3">
<!-- EDIT ARTICLE -->
<form method="post" style="box-sizing:content-box">
    <label> 
        <strong>Titel</strong>
    </label>
    <br />
    <input asp-for="NewArticle.Title" type="text" />
    <br />


    <label>
        <strong>Brødtekst</strong>
    </label>
    <br />
    <textarea asp-for="NewArticle.Content" rows="10" cols="40"></textarea>
    <br />

    <button type="submit" class="btn btn-success mb-2">Rediger</button>

</form> 
</div>





















@* 
<form method="post">
    <div class="form-group">
        <label for="editArticleTitleInput">Title</label>
        <input type="text" class="form-control" name="editArticleTitleInput" value="@Model.ArticleToEdit.Title">
    </div>
    <div class="form-group">
        <label for="editArticleContentInput">Content</label>
        <input type="text" class="form-control" name="editArticleContentInput" value="@Model.ArticleToEdit.Content">
    </div>
    <p>
        <button type="submit" class="btn btn-primary mb-2">Save changes</button>
    </p>
</form> *@




@* <form method="post">
    <input asp-for="@Model.ArticleTitle" type="text" value="@Model.ArticleToEdit.Title" />
</form> *@

Tenn.is/Pages/Articles/Index.cshtml
@page
@using Tennis.Models
@model Tennis.Pages.Articles.IndexModel
@{
}


<div class="card cardouter p-3 container-fluid">
<!-- CREATE NEW ARTICLE BUTTON -->
<span>
    <a class="btn btn-outline-success rounded-pill" asp-page="/Articles/CreateArticle" style="float:left">
        Lav ny artikel
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-plus" viewBox="0 0 16 16">
            <path d="M8 6.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 .5-.5" />
            <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z" />
        </svg>
    </a>
</span>
<br />
<br />

<!-- SEARCH AREA -->
<div class="sticky-top float-end p-2 w-100">
    <form method="get" class="float-end">
        <input type="text" asp-for="@Model.SearchFilter" onchange="this.form.submit()" placeholder="Søg..." />
        <button>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
        </button>
        <br />
        <input type="checkbox" data-val="true" id="IsChecked" name="IsChecked" value="true" @(Model.IsChecked ?"checked='checked'":"")>
        Søg i brødtekst?
        <input name="IsChecked" type="hidden" value="false">
    </form>


@* 
    <form method="post" asp-page-handler="sorting">
        <h4>
            Oprettet
        </h4>
        <input asp-for="Sorting" type="radio" value="Timeasc" id="Sorting" name="Sorting" />Timeasc<br />
        <input asp-for="Sorting" type="radio" value="Timedesc" id="Sorting" name="Sorting" />Timedesc<br />
        <h4>
            Redigeret
        </h4>
        <input asp-for="Sorting" type="radio" value="Editasc" id="Sorting" name="Sorting" />Editasc<br />
        <input asp-for="Sorting" type="radio" value="Editdesc" id="Sorting" name="Sorting" />Editdesc<br />
        <h4>
            Forfatter
        </h4>
        <input asp-for="Sorting" type="radio" value="Authorasc" id="Sorting" name="Sorting" />Authorasc<br />
        <input asp-for="Sorting" type="radio" value="Authordesc" id="Sorting" name="Sorting" />Authordesc<br />
        <button type="submit"> sorter</button>
    </form>
    

    <h3>@Model.Sorting</h3> *@

</div>



<!-- NEWSFEED -->
@foreach (var a in Model.AllArticles) {

    <!-- ONE ARTICLE CARD -->
    <p class="align-items-md-center">
        <div class="card" style="width: 45rem;">
            <div class="card-body">
                <h4 class="card-title text-decoration-underline">
                    <strong>
                        @a.Title
                    </strong>
                </h4>

                @if (a.AuthorID != null) {
                    <h7 class="card-subtitle mb-2 text-muted">
                        - a.AuthorID,
                    </h7>
                }
                else {
                    <h7 class="card-subtitle mb-2 text-muted">
                        - Slettet bruger,
                    </h7>
                }

                <h7 class="card-subtitle mb-2 text-muted">
                    @a.TimeStamp
                </h7>

                <h6 class="card-footer card mb-2 text-body">
                <p class="card-text">
                    @a.Content
                    <br />
                    <br />
                </p>
                </h6>

                @if (a.ImgPath != null) {
                    <img class="card-img" src="..." alt="@a.Title" />
                }

                @if (a.LastEdited != null && a.LastEdited != a.TimeStamp) {
                    <h7 class="card-subtitle mb-2 text-muted">
                        Sidst redigeret: @a.LastEdited
                    </h7>
                }
            </div>
            <footer class="p-1">
                <span>
                    <a class="btn btn-outline-info rounded-pill btn-sm" asp-page="/Articles/EditArticle" asp-route-id="@a.ArticleID" style="float:left">
                        Rediger
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z" />
                        </svg>
                        </a>
                </span>
                <span>
                    <form asp-page-handler="delete" method="post">
                        <button class="btn btn-outline-danger rounded-pill btn-sm" style="float:right">
                            Slet
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                            </svg>
                        </button>
                        <input type="hidden" name="id" value="@a.ArticleID" />
                    </form>
                </span>
            </footer>
        </div>
    </p>

}
</div>