Tenn.is/Models/Lane.cs
namespace Tennis.Models
{
    public class Lane
    {

        public int Id { get; set; }
        public bool OutDoor { get; set; }
        public bool PadelTennis { get; set; }

        public Lane(int id, bool outDoor, bool padelTennis)
        {
            Id = id;
            OutDoor = outDoor;
            PadelTennis = padelTennis;
        }

        public Lane()
        {
            
        }

        public override string ToString()
        {
            return $"";
        }
    }
}

Tenn.is/Pages/Lanes/BookingSuccess.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Pages.Lanes
{
    public class BookingSuccessModel : PageModel
    {

        public string BookingDate { get; set; }
        public string Partner { get; set; }
        public string Lane { get; set; }

        public void OnGet(string lane, string mate, string date)
        {
            BookingDate = date;
            Partner = mate;
            Lane = lane;
        }
    }
}

Tenn.is/Pages/Lanes/LaneCreate.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Pages.Lanes
{
    public class LaneCreateModel : PageModel
    {
        ILaneService Service;
        [BindProperty]
        public Lane NewLane{ get; set; }

        public LaneCreateModel(ILaneService service)
        {
            Service = service;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostCreate() 
        {
            Service.CreateLane(NewLane);
            return RedirectToPage("LaneIndex");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("LaneIndex");
        }
    }
}

Tenn.is/Pages/Lanes/LaneDelete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Pages.Lanes
{
    public class LaneDeleteModel : PageModel
    {
        ILaneService Service;
        [BindProperty]
        public Lane DelLane { get; set; }

        public LaneDeleteModel(ILaneService service)
        {
            Service = service;
        }

        public IActionResult OnGet(int Id)
        {
            DelLane = Service.GetLaneByNumber(Id);
            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            Service.DeleteLane(id);
            return RedirectToPage("LaneIndex");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("LaneIndex");
        }
    }
}

Tenn.is/Pages/Lanes/LaneIndex.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Pages.Lanes
{
    public class LaneIndexModel : PageModel
    {
        ILaneService Service;
        public List<Lane> LaneList { get; set; }

        public LaneIndexModel(ILaneService service)
        {
            Service = service;
        }

        public void OnGet()
        {
            LaneList = Service.GetAllLanes();
        }


    }
}

Tenn.is/Pages/Lanes/LaneUpdate.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Pages.Lanes
{
    public class LaneUpdateModel : PageModel
    {
        ILaneService Service;
        [BindProperty]
        public Lane LaneToUpdate { get; set; }
        [BindProperty]
        public int Id { get; set; }

        public LaneUpdateModel(ILaneService service)
        {
            Service = service;
        }

        public IActionResult OnGet(int id)
        {            
            LaneToUpdate = Service.GetLaneByNumber(id);
            Id = id;
            return Page();
        }

        public IActionResult OnPostUpdate(int id)
        {
            Service.EditLane(LaneToUpdate, id);
            return RedirectToPage("LaneIndex");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("LaneIndex");
        }

    }
}

Tenn.is/Pages/Lanes/BookingCancel.cshtml
@page "{bookingid:int}"
@model Tennis.Pages.Lanes.BookingCancelModel
@{
    ViewData["Title"] = "Aflys banebooking";
}
<div class="card cardouter p-3" align="center">
    <div class="card cardfocus p-3">
<h1 class="display-4 text-danger">Aflys booking</h1>
<p class="text-danger">@Model.Message</p>

@if (Model.CurrentBooking != null)
{
    <form method="post">
        <div class="form-group">
            <p>Du er ved at aflyse din booking mellem <b>@Model.Booker.FirstName @Model.Booker.LastName</b> og <b>@Model.Mate.FirstName @Model.Mate.LastName</b>,</p>
            <p>Bane @Model.CurrentBooking.LaneNumber,  @Model.CurrentBooking.DateStart.ToShortDateString() kl. @Model.CurrentBooking.DateStart.ToShortTimeString()</p>
            <br />
            <p>Bare rolig, din tennismakker bliver informeret om aflysningen.</p>
            <br />

            <input type="submit" asp-page-handler="Delete" asp-route-bookingid="@Model.CurrentBooking.BookingID" class="btn btn-danger" value="Aflys" />

            <input type="submit" asp-page-handler="Cancel" class="btn btn-outline-secondary" value="Fortryd" />
        </div>
    </form>
}
else if (Model.CurrentBookingTraining != null)
{
    <form method="post">
        <div class="form-group">
            <p>Du er ved at aflyse din booking i træningsholdet <b>@Model.TrainingTeam.Title</b>,</p>
            <p>Bane @Model.CurrentBookingTraining.LaneNumber,  @Model.CurrentBookingTraining.DateStart.ToShortDateString() kl. @Model.CurrentBookingTraining.DateStart.ToShortTimeString()</p>
            <br />
         
            <input type="submit" asp-page-handler="Delete" asp-route-bookingid="@Model.CurrentBookingTraining.BookingID" class="btn btn-danger" value="Aflys" />

            <input type="submit" asp-page-handler="Cancel" class="btn btn-outline-secondary" value="Fortryd" />
        </div>
    </form>
}
</div>
</div>

Tenn.is/Pages/Lanes/BookingCreate.cshtml
@page
@model Tennis.Pages.Lanes.BookingCreateModel
@{
    ViewData["Title"] = "Book en bane";
}
<div class="d-flex row card cardgold">
    <h3 class="display-4">Din booking:</h3>
    <form method="post" class="container row p-3">
        <div class="col-md card cardouter p-3 m-2">
        <input type="hidden" asp-for="@Model.CurrentBooking.LaneNumber" />
        <input type="hidden" asp-for="@Model.CurrentBooking.BookingID" />
        <input type="hidden" asp-for="@Model.CurrentBooking.UserID" />
        <input type="hidden" asp-for="@Model.CurrentBooking.DateStart" />
        <input type="hidden" asp-for="@Model.CurrentBooking.Cancelled" />
        <h4 class=" textmain">Bane @Model.LaneInfo.Id :
            @if(Model.LaneInfo.OutDoor)
            {
                <span>Udendørs </span>
            } else
            {
                <span>Indendørs </span>
            }
            @if(Model.LaneInfo.PadelTennis)
            {
                <span>padeltennis</span>
            } else
            {
                <span>tennis</span>
            }
        </h4>
        <h4 class=" textmain">
            Tidspunkt: @Model.CurrentBooking.DateStart
        </h4>
            @if(Model.CheckMaximum(Model.CurrentUser))
            {
                <span class="text-danger">Du har allerede 4 bookinger i de næste 14 dage. For at lave nye bookinger, skal du enten aflyse en nuværende booking, eller vente til en af dine bookinger er overstået.</span>
            } else if(Model.AlreadyBooked(Model.CurrentUser))
            {
                <span class="text-danger">Du er allerede booket på en anden bane på dette tidspunkt.</span>
            }
            <br />
        </div>
        <div class="col-md card cardfocus p-3 m-2">
        <div style="overflow-y:scroll">
            <table class="table">
                <thead class="lighttablehead">
                    <tr>
                        <td>
                                <h4>Vælg venligst tennismakker</h4>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.AvailableUsers)
                    {
                            string buttonvalue = user.UserId < 0 ? user.Username : $"{user.FirstName} {user.LastName}";
                            string color = user.UserId < 0 ? "primary" : "success";
                            if (!Model.CheckMaximum(Model.CurrentUser) && !Model.AlreadyBooked(Model.CurrentUser) && !Model.CheckMaximum(user) && !Model.AlreadyBooked(user))
                            {
                                    <tr>
                                        <td>
                                            <input type="submit" asp-page-handler="Book" asp-route-partnerid="@user.UserId" value="@buttonvalue" class="btn btn-outline-@color w-100 border-0" />
                                        </td>
                                    </tr>
                            }
                            else
                            {
                                    <tr class="table-secondary">
                                        <td>
                                            <input type="submit" asp-page-handler="Book" asp-route-partnerid="@user.UserId" value="@buttonvalue" class="btn btn-outline-danger w-100 border-0 disabled" />
                                        </td>
                                    </tr>
                                }
                            }
                </tbody>
            </table>
        </div>
        </div>
        <br />
    </form>
@*     <form method="get" class="container col-md-6 card">
        <input type="hidden" asp-for="@Model.SelectedDay" />
        <input type="hidden" asp-for="@Model.Partner.UserId" />
        <div class="form-group">
        <input asp-for="@Model.Partner.Username" type="text" class="form-control" placeholder="Vælg en makker nedenunder" readonly />
        </div>
       
    </form> *@
</div>

Tenn.is/Pages/Lanes/BookingCreateTraining.cshtml
@page "{laneid}/{trainingTeamID}/{datetime}"
@model Tennis.Pages.Lanes.BookingCreateTrainingModel
@{
    ViewData["Title"] = "Book en bane til træningshold";
}
<h3>Din booking:</h3>
<form method="post" class="container row">
    <div class="col-md-6 card">
    
    <p>Bane @Model.Lane.Id :
        @if(Model.Lane.OutDoor)
        {
            <span>Udendørs </span>
        } else
        {
            <span>Indendørs </span>
        }
        @if(Model.Lane.PadelTennis)
        {
            <span>padeltennis</span>
        } else
        {
            <span>tennis</span>
        }
    </p>
    <p>
        Tidspunkt: @Model.SelectedDay
    </p>
        <input type="submit" value="Book" class="btn btn-outline-success w-100 border-0" />
        <input type="submit" asp-page-handler="Cancel" value="Fortryd" class="btn btn-outline-danger w-100 border-0" />
    </div>
</form>

Tenn.is/Pages/Lanes/BookingOverview.cshtml
@page "{trainingTeamID?}"
@using Tennis.Interfaces
@inject ILaneBookingService _laneBookingService
@model Tennis.Pages.Lanes.BookingOverviewModel
@{
    ViewData["Title"] = "Baner";
}
<form method="get" class="card cardgold p-3">
    <div class="row">
@* <form method="get" class="container row justify-content-start"> *@
<div class="container col-md-6 row card cardouter p-3 mx-0">
        <p class="textdark">Søgekriterier:</p>
        <div class="row">
    <div class="col">

    <span>Fra </span><select asp-for="@Model.StartFilter" asp-items="@Model.FromOptions" onchange="this.form.submit()"></select>
    <br />
        <span>Til </span><select asp-for="@Model.EndFilter" asp-items="@Model.ToOptions" onchange="this.form.submit()"></select>
        </div>
        <div class="col">
            <input class="form-check-input" asp-for="TennisFilter" onclick="this.form.submit()"  />
            <label for="TennisFilter">Tennis</label><br>
            <input class="form-check-input" asp-for="PadelFilter" onclick="this.form.submit()"  />
            <label for="PadelFilter">Padel</label>
        </div>
        <div class="col">
            <input class="form-check-input" asp-for="InsideFilter" onclick="this.form.submit()" />
            <label for="InsideFilter">Indendørs</label><br>
            <input class="form-check-input" asp-for="OutsideFilter" onclick="this.form.submit()" />
            <label for="OutsideFilter">Udendørs</label>
        </div>
        </div>
        <span class="text-danger">@Model.BookingError</span>
</div>
@* <div class="container col-md-6 row card cardouter p-3 mx-0">
</div> *@
</div>
@* </form> *@
<div class="d-flex row justify-content-start" style="height: 500px">

<div class="col-md-6 card cardfocus p-3">
        <form method="get" class="container">
        <div align="center">
        <select asp-for="@Model.SelectedMonth" asp-items="@Model.SelectOptions" onchange="this.form.submit()"></select>
    </div>
    <div class="container">
    <table class="table table-borderless m-auto">
        <thead class="lighttablehead">
            <tr>
                <th class="text-center" style="width: 14%">
                    Søn
                </th>
                            <th class="text-center" style="width: 14%">
                    Man
                </th>
                            <th class="text-center" style="width: 14%">
                    Tir
                </th>
                            <th class="text-center" style="width: 14%">
                    Ons
                </th>
                            <th class="text-center" style="width: 14%">
                    Tor
                </th>
                            <th class="text-center" style="width: 14%">
                    Fre
                </th>
                            <th class="text-center" style="width: 14%">
                    Lør
                </th>
            </tr>
        </thead>
        <tbody class="lighttable">
            @for(int week=0; week<6; week++)
            {
                <tr>
                    @for(int weekday=1; weekday<=7; weekday++)
                    {
                    int totalIteration = (weekday + (week * 7));

                                    @if (Model.FirstOfTheWeek < totalIteration && totalIteration < (Model.DatesOfTheMonth.Count + 1 + Model.FirstOfTheWeek))
                                    {
                                        DateTime actualDate = Model.DatesOfTheMonth[totalIteration - Model.FirstOfTheWeek - 1];
                                        if (Model.SelectedDay != null && Model.SelectedDay.Value.Day == actualDate.Day)
                                        {
                                            @:<td class="table-warning border" align="center">
                                        }
                                        else
                                        {
                                            @:<td class="border" align="center">
                                        }
                                                <button class="w-100" type="submit"
                                                value="@actualDate.ToString()"
                                                name="DateString"
                                                style="border: none; margin:auto; padding: 0px; background-color: transparent;">
                                                    <div class="w-100">
                                                        <span class="text-black-50">@actualDate.Day</span>
                                                    </div>
                                                    <div class="w-100 py-2" style="font-size: 35%; word-spacing: -1px">
                                                        @foreach (var item in @Model.Lanes)
                                                        {
                                                            if (Model.CheckFilters(item))
                                                            {
                                                            if (actualDate.Date >= DateTime.Now.Date && actualDate.Date <= DateTime.Now.AddDays(14).Date)
                                                            {
                                                                @* int existingbookings = Model.Bookings.Where(b =>
                                                                b.LaneNumber == item.Id &&
                                                                b.DateStart.Day == actualDate.Day &&
                                                                b.DateStart.Month == Model.SelectedMonth).
                                                                Count(); *@
                                                                int existingbookings = _laneBookingService.GetNoOfBookings(item.Id, actualDate.AddHours(Model.StartFilter), actualDate.AddHours(Model.EndFilter));
                                                                int possiblebookings = Model.EndFilter - Model.StartFilter;
                                                                if (Model.StartFilter < Model.EndFilter && existingbookings < possiblebookings)
                                                                {
                                                                    if (possiblebookings - existingbookings > 1)
                                                                    {
                                                                        <span>&#129001;</span>
                                                                    }
                                                                    else
                                                                    {
                                                                        <span>&#129000;</span>
                                                                    }
                                                                }
                                                                else
                                                                {
                                                                    <span>&#128997;</span>
                                                                }
                                                            } else
                                                            {
                                                                <span>&#9633;</span>
                                                            }
                                                        }
                                                        }
                                                    </div>
                                                </button>
                                            @:</td>
                                    } 
                                    else
                                        {
                                            <td></td>
                                        }
                    }
                </tr>
            }
        </tbody>
    </table>
    <span class="text-black-50 small">&#129001; = 2 eller flere tider tilbage</span>
    <span class="text-black-50 small">&#129000; = 1 tid tilbage</span>
    <span class="text-black-50 small">&#128997; = Ingen tider tilbage</span>
            </div>
            </form>
</div>

    @if(Model.SelectedDay != null)
    {
        <div class="container-fluid col-md-6 border cardfocus p-3" align="center" style="max-height: 500px; overflow-y: scroll">
            <h3 class="display-6">@Model.SelectedDay.Value.Date.ToShortDateString()</h3>
            <table class="table table-bordered table-hover">
                <thead class="lighttablehead">
                    <tr>
                        <th style="width:20%">
                            <p>Tider:</p>
                        </th>
                        @foreach(var item in Model.Lanes)
                        {
                            <th>
                                <span>Bane 
                                    <span>@item.Id</span><br />
                                        @if (item.OutDoor)
                                        {
                                            <span>Udendørs</span>
                                        } else
                                        {
                                            <span>Indendørs</span>
                                        }
                                        @if(item.PadelTennis)
                                        {
                                            <span>(P)</span>
                                        }
                                    </span>
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @for(int hour=8; hour<=21; hour++)
                    {
                        <tr>
                            <td class="lighttable">
                                <span>@hour</span> - <span>@(hour+1)</span>
                            </td>
                            @foreach(var item in Model.Lanes)
                            {
                                    DateOnly currentDay = DateOnly.FromDateTime(Model.SelectedDay.Value);
                                    TimeOnly currentTime = new TimeOnly(hour, 0);
                                    DateTime currentDayAndTime = new DateTime(currentDay, currentTime);
                                    @* bool foundBooking = Model.UnfilteredBookings.Where(b => b.DateStart == currentDayAndTime && b.LaneNumber == item.Id).Count() > 0; *@
                                    bool foundBooking = _laneBookingService.IsLaneBooked(item.Id, currentDayAndTime) != null;
                                    if(foundBooking)
                                    {
                                        <td>
                                            <span class="btn btn-outline-danger disabled w-100 border-0" style="font-weight:600">Booket</span>
                                        </td>
                                    } else if(currentDayAndTime >= DateTime.Now && currentDayAndTime <= DateTime.Now.AddDays(14)) {
                                    <td>
                                    @if (Model.TrainingTeamID == null)
                                            {
                                                <a asp-page="BookingCreate" asp-route-laneid="@item.Id" asp-route-datetime="@currentDayAndTime.ToString()" class="btn btn-outline-success w-100 border-0" style="font-weight:600">Ledig</a>
                                            }
                                            else
                                            {
                                                <a asp-page="BookingCreateTraining" asp-route-laneid="@item.Id" asp-route-trainingTeamID="@Model.TrainingTeamID" asp-route-datetime="@currentDayAndTime.ToString("O")" class="btn btn-outline-success w-100 border-0" style="font-weight:600">Ledig</a>
                                            }
                                            </td>
                                    } else
                                    {
                                        <td>
                                            <span class="btn btn-outline-secondary disabled w-100 border-0" style="font-weight:600">Utilgængelig</span>
                                        </td>
                                    }
                            }
                        </tr>
                    }
                </tbody>
            </table>
            </div>
    }
</div>
</form>

Tenn.is/Pages/Lanes/BookingSuccess.cshtml
@page
@model Tennis.Pages.Lanes.BookingSuccessModel
@{
    ViewData["Title"] = "Bane booket!";

}
<div class="card cardouter p-3" align="center">
    <h3 class="display-4 textaccent">Banen er booket!</h3>
    <div class="card cardfocus p-3">
    <p class="textdark">Vi har modtaget din booking til <b class="textmain">@Model.Lane</b> med <b class="textmain">@Model.Partner</b>.</p>
    <p class="textdark">Banen er jeres <b class="textmain">@Model.BookingDate</b>.</p>
    <br />
    <p class="textmain">Husk: Hvis I er forhindret i at spille, er det god stil at aflyse banebookingen. Du kan se/aflyse dine banebookings på din <a asp-area="" asp-page="/Users/Index">profilside</a>.</p>
    <p class="textaccent">Har du lyst til at spille mere? <a asp-area="" asp-page="/Lanes/BookingOverview" asp-page-handler="FirstClick">Vend tilbage til banebooking her!</a></p>
    </div>
</div>

Tenn.is/Pages/Lanes/LaneCreate.cshtml
@page
@model Tennis.Pages.Lanes.LaneCreateModel
@{
    ViewData["Title"] = "LaneCreate";
}
<div class="card container-fluid cardgold">
    <div class="card container-fluid lighttablehead">
<h1>skab en ny banne</h1>
    </div>
<div class="row">
        <div class="container col-md card cardfocus">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.NewLane.Id" class="control-label"></label>
                <input asp-for="@Model.NewLane.Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.NewLane.OutDoor" class="control-label"></label>
                <input asp-for="@Model.NewLane.OutDoor"/>
            </div>
            <div class="form-group">
                <label asp-for="@Model.NewLane.PadelTennis" class="control-label"></label>
                <input asp-for="@Model.NewLane.PadelTennis"/>
            </div>

            <div class="form-group">
                    <input type="submit" value="Skab" asp-page-handler="Create" class="btn btn-outline-success" />
                    <input type="submit" value="Fortryd" asp-page-handler="Cancel" class="btn btn-outline-secondary"  />
            </div>
        </form>
    </div>
</div>
</div>

Tenn.is/Pages/Lanes/LaneDelete.cshtml
@page
@model Tennis.Pages.Lanes.LaneDeleteModel
@{
    ViewData["Title"] = "LaneDelete";
}

<div class="card container-fluid cardgold">
<div class="card container-fluid lighttablehead">
<h1>fjern bannen</h1>
</div>
    <div class="container col-md card cardfocus">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.DelLane.Id" class="control-label"></label> <p>@Model.DelLane.Id</p>
            </div>
            <div class="form-group">
                <label asp-for="@Model.DelLane.OutDoor" class="control-label"></label> <p>@Model.DelLane.OutDoor</p>
            </div>
            <div class="form-group">
                <label asp-for="@Model.DelLane.PadelTennis" class="control-label"></label> <p>@Model.DelLane.PadelTennis</p>
            </div>

            <div class="form-group">
                <input type="submit" value="Fjern" asp-page-handler="Delete"  asp-route-id="@Model.DelLane.Id" class="btn btn-outline-danger" />
                    <input type="submit" value="Fortryd" asp-page-handler="Cancel"  class="btn btn-outline-secondary" />
            </div>
        </form>
    </div>
</div>
</div>

Tenn.is/Pages/Lanes/LaneIndex.cshtml
@page
@model Tennis.Pages.Lanes.LaneIndexModel
@{
    ViewData["Title"] = "LaneIndex";
}

<div class="card container-fluid cardgold">
    <div class="card container-fluid cardouter">
<h3>Liste af banner </h3>
<p>
    <a asp-page="LaneCreate" class="btn btn-outline-secondary">Lav en ny banne</a>
</p>
</div>

    <div class="container col-md card cardfocus">

<table class="table">
    <thead class="lighttablehead">
        <tr>
            <th>
                Banenummer
            </th>
            <th>
                Udenfor/indenfor
            </th>
            <th>
                Banetype
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody class="lighttable">
        @if (Model.LaneList.Count != 0)
        {
            @foreach (var item in Model.LaneList)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>

                        @if (item.OutDoor == true)
                        {
                            <p>Udenfor</p>
                        }
                        else
                        {
                            <p>Indenfor</p>
                        }
                    </td>
                    <td>
                        @if (item.PadelTennis == true)
                        {
                            <p>Padel</p>
                        }
                        else
                        {
                            <p>Tennis</p>
                        }
                    </td>
                    <td>
                                <a asp-page="LaneDelete" asp-route-Id="@item.Id" class="btn btn-outline-danger">Fjern</a>|

                                <a asp-page="LaneUpdate" asp-route-Id="@item.Id" class="btn btn-outline-secondary">Opdater</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
</div>
</div>

Tenn.is/Pages/Lanes/LaneUpdate.cshtml
@page
@model Tennis.Pages.Lanes.LaneUpdateModel
@{
    ViewData["Title"] = "LaneUpdate";
}

<div class="card container-fluid cardgold">
    <div class="card container-fluid lighttablehead">
<h1>Opdater bannen</h1>
</div>
    <div class="container col-md card cardfocus">
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.LaneToUpdate.Id" class="control-label"></label>
                <input asp-for="@Model.LaneToUpdate.Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.LaneToUpdate.OutDoor" class="control-label"></label>
                <input asp-for="@Model.LaneToUpdate.OutDoor"/>
                
            </div>
            <div class="form-group">
                <label asp-for="@Model.LaneToUpdate.PadelTennis" class="control-label"></label>
                <input asp-for="@Model.LaneToUpdate.PadelTennis"/>
            </div>

            <div class="form-group">
                        <input type="submit" value="Opdater" asp-page-handler="Update" asp-route-id="@Model.LaneToUpdate.Id" class="btn btn-outline-success"  />
                <input type="submit" value="Fortryd" asp-page-handler="Cancel" class="btn btn-outline-secondary" />
            </div>
        </form>
    </div>
</div>
</div>
</div>